services:
  app:
    image: flight-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: flight-frontend-dev
    networks:
      - app-network

  server:
    image: flight-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: flight-backend-dev
    networks:
      - app-network

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: flight-reverse-proxy
    depends_on:
      - app
      - server
    networks:
      - app-network

networks:
  app-network:
    external: true
